sudo: required
services:
  - docker

before_install:
  - docker build -t rodjuanma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rodjuanma/react-test npm run test -- --coverage

after_succes:
  - docker build -t rodjuanma/multi-client ./client
  - docker build -t rodjuanma/multi-nginx ./nginx
  - docker build -t rodjuanma/multi-server ./server
  - docker build -t rodjuanma/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rodjuanma/multi-client
  - docker push rodjuanma/multi-nginx
  - docker push rodjuanma/multi-server
  - docker push rodjuanma/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-625599708654
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
